/**
 * Ported from Replit V1 game-data.ts — all 20 cities preserved
 * Game data for Beat World 2.0 including cities, instruments, guest producers, and game progression
 */

/**
 * @typedef {Object} Instrument
 * @property {string} id
 * @property {string} name
 * @property {string} type - 'kick' | 'snare' | 'hihat' | 'perc' | 'bass' | 'lead' | 'chord' | 'arp' | 'pad' | 'fx'
 * @property {string} color - Tailwind CSS class for visualization
 */

/**
 * @typedef {Object} GenreIntro
 * @property {string} about
 * @property {string} bpmRange
 * @property {string[]} tips
 */

/**
 * @typedef {Object} GuestProducer
 * @property {string} name
 * @property {string} quote
 * @property {string} skinTone - Hex color
 * @property {string} topColor - Hex color
 * @property {string} accessory
 * @property {GenreIntro} [genreIntro]
 * @property {string} [masteringComment]
 */

/**
 * @typedef {Object} TimeSignature
 * @property {number} numerator
 * @property {number} denominator
 * @property {number} stepsPerBeat
 */

/**
 * @typedef {Object} CityLevel
 * @property {string} id
 * @property {string} name
 * @property {string} genre
 * @property {number} level
 * @property {number} numInstruments
 * @property {Instrument[]} instruments
 * @property {[number, number, number]} position
 * @property {string} venue
 * @property {string} mediaOutlet
 * @property {string} emoji
 * @property {number} [defaultBpm]
 * @property {GuestProducer} guestProducer
 * @property {string} region
 * @property {TimeSignature} [timeSignature]
 */

export const CITIES = {
  'new-york': {
    id: 'new-york',
    name: 'New York',
    genre: 'Hip Hop',
    level: 1,
    numInstruments: 4,
    instruments: [
      { id: 'kick1', name: '808 Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare1', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat1', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'bass1', name: 'Sub Bass', type: 'bass', color: 'bg-purple-500' },
    ],
    position: [-3.5, 0, -0.5],
    venue: 'Madison Square Garden',
    mediaOutlet: 'XXXS',
    emoji: '🗽',
    defaultBpm: 90,
    studioBackdrop: '/assets/sprites/venues/studio-nyc.png',
    performanceBackdrop: '/assets/sprites/venues/gig-bk-court.png',
    chordProgressionNames: ['BOOM BAP', 'G-FUNK', 'TRAP', 'SOUL LOOP'],
    guestProducer: {
      name: 'DJ PRIMO',
      quote: 'CHOP THE SAMPLE, FLIP THE BEAT. BOOM BAP FOREVER.',
      skinTone: '#8d5524',
      topColor: '#111133',
      accessory: 'headphones',
      genreIntro: {
        about: 'HIP HOP WAS BORN IN THE BRONX IN THE 1970S. BOOM BAP IS THE HEARTBEAT OF NYC — DUSTY SAMPLES, HARD DRUMS, RAW BARS.',
        bpmRange: '85-95 BPM',
        tips: ['KEEP THE KICK AND SNARE PUNCHY', 'LEAVE SPACE FOR THE MC', 'CHOP A SOUL SAMPLE FOR THE VIBE'],
      },
      masteringComment: 'YO, THIS BEAT IS CRAZY! THE BOOM BAP GODS WOULD BE PROUD. LETS RUN IT!',
    },
    region: 'north-america',
  },
  'los-angeles': {
    id: 'los-angeles',
    name: 'Los Angeles',
    genre: 'West Coast Rap',
    level: 1,
    numInstruments: 6,
    instruments: [
      { id: 'kick2', name: 'G-Funk Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare2', name: 'Crisp Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat2', name: 'Ride Cymbal', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'bass2', name: 'P-Funk Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead2', name: 'Synth Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord2', name: 'Strings', type: 'chord', color: 'bg-blue-500' },
    ],
    position: [-4.5, 0.5, -1],
    venue: 'The Forum',
    mediaOutlet: 'Rap-Up',
    emoji: '☀️',
    defaultBpm: 95,
    guestProducer: {
      name: 'KURUPT MC',
      quote: 'G-FUNK RUNS THESE STREETS. WEST COAST FOREVER.',
      skinTone: '#5d4e37',
      topColor: '#0066ff',
      accessory: 'sunglasses',
      genreIntro: {
        about: 'G-FUNK EMERGED FROM LA IN THE 1990S. IT\'S THE FUNK OF GEORGE CLINTON MIXED WITH HARD WEST COAST GANGSTA RAP. SYNTHS, FUNK BASS, AND ATTITUDE.',
        bpmRange: '90-100 BPM',
        tips: ['LAYER YOUR SYNTHS', 'MAKE THE BASS TALKATIVE', 'KEEP DRUMS ROLLING'],
      },
      masteringComment: 'THIS BEAT SLAPS LIKE THE GOLDEN ERA. LOVE THE SYNTH LAYERS!',
    },
    region: 'north-america',
  },
  'detroit': {
    id: 'detroit',
    name: 'Detroit',
    genre: 'Techno',
    level: 1,
    numInstruments: 8,
    instruments: [
      { id: 'kick3', name: '4x4 Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare3', name: 'Clap', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat3', name: 'Metal Hihat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc3', name: 'Cowbell', type: 'perc', color: 'bg-green-500' },
      { id: 'bass3', name: 'Sine Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead3', name: 'Square Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'pad3', name: 'Pad Synth', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx3', name: 'Reverb FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3, -0.5, 0],
    venue: 'Movement Festival',
    mediaOutlet: 'Resident Advisor',
    emoji: '🏭',
    defaultBpm: 120,
    guestProducer: {
      name: 'DERRICK MAY',
      quote: 'TECHNO IS LIKE AN EMPTY CANVAS. YOU CREATE THE UNIVERSE.',
      skinTone: '#5d4e37',
      topColor: '#1a1a1a',
      accessory: 'chain-necklace',
      genreIntro: {
        about: 'TECHNO WAS BORN IN DETROIT IN THE EARLY 1980S. IT\'S THE SOUND OF THE FUTURE, MECHANICAL AND HYPNOTIC. FOUR-ON-THE-FLOOR WITH LAYERED SYNTHS.',
        bpmRange: '115-130 BPM',
        tips: ['BUILD YOUR LAYERS GRADUALLY', 'USE REVERB TO CREATE SPACE', 'LET THE KICK DRIVE THE GROOVE'],
      },
      masteringComment: 'PURE DETROIT SPIRIT. THE LAYERS ARE PERFECTLY WOVEN. BEAUTIFUL WORK!',
    },
    region: 'north-america',
  },
  'puerto-rico': {
    id: 'puerto-rico',
    name: 'Puerto Rico',
    genre: 'Reggaeton',
    level: 2,
    numInstruments: 6,
    instruments: [
      { id: 'kick4', name: 'Perreo Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare4', name: 'Snare Crunch', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat4', name: 'Hi-Hat Roll', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc4', name: 'Guiro', type: 'perc', color: 'bg-green-500' },
      { id: 'bass4', name: 'Reggaeton Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead4', name: 'Synth Hook', type: 'lead', color: 'bg-pink-500' },
    ],
    position: [-2.5, 1.5, 0.5],
    venue: 'Coliseo de Puerto Rico',
    mediaOutlet: 'CORNPLEX',
    emoji: '🏝️',
    defaultBpm: 92,
    studioBackdrop: '/assets/sprites/venues/studio-pr.png',
    performanceBackdrop: '/assets/sprites/venues/gig-pr-block-party.png',
    chordProgressionNames: ['DEMBOW BASE', 'PERREO MINOR', 'SAN JUAN PIANO', 'REGGAETON ROMÁNTICO'],
    guestProducer: {
      name: 'DADDY YANKEE',
      quote: 'DALE! REGGAETON IS THE VOICE OF THE STREETS.',
      skinTone: '#a0725f',
      topColor: '#ff6600',
      accessory: 'gold-chain',
      genreIntro: {
        about: 'REGGAETON EMERGED IN PUERTO RICO IN THE 1990S. IT\'S THE RHYTHM OF THE CARIBBEAN MIX WITH HIP-HOP ATTITUDE. THE DEMBOW RHYTHM IS THE FOUNDATION.',
        bpmRange: '85-105 BPM',
        tips: ['THE DEMBOW RHYTHM IS KEY', 'KEEP THE KICK TIGHT AND PUNCHY', 'LAYER SYNTHS FOR THAT MELODIC HOOK'],
      },
      masteringComment: 'DALE! THIS BEAT IS FIRE! THE DEMBOW IS PERFECT!',
    },
    region: 'caribbean',
  },
  'dominican-republic': {
    id: 'dominican-republic',
    name: 'Dominican Republic',
    genre: 'Merengue / Bachata',
    level: 2,
    numInstruments: 8,
    instruments: [
      { id: 'kick5', name: 'Merengue Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare5', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat5', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc5', name: 'Timpani', type: 'perc', color: 'bg-green-500' },
      { id: 'bass5', name: 'Bass Line', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead5', name: 'Tres Guitar', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord5', name: 'String Section', type: 'chord', color: 'bg-blue-500' },
      { id: 'pad5', name: 'Pad Backdrop', type: 'pad', color: 'bg-indigo-500' },
    ],
    position: [-2.3, 1.8, 0.7],
    venue: 'Teatro Nacional',
    mediaOutlet: 'Bachata Urbano',
    emoji: '💃',
    guestProducer: {
      name: 'JUAN LUIS GUERRA',
      quote: 'MERENGUE IS THE HEARTBEAT OF THE CARIBBEAN.',
      skinTone: '#a0725f',
      topColor: '#ff0066',
      accessory: 'fedora',
      genreIntro: {
        about: 'MERENGUE AND BACHATA ARE THE SOUL OF THE DOMINICAN REPUBLIC. MERENGUE IS FAST AND ENERGETIC WITH QUICK HIP MOVEMENTS. BACHATA IS SLOWER, MORE ROMANTIC AND INTIMATE.',
        bpmRange: '120-130 BPM (MERENGUE), 60-80 BPM (BACHATA)',
        tips: ['KEEP THE RHYTHM INFECTIOUS', 'USE ACOUSTIC ELEMENTS', 'LAYER STRINGS FOR EMOTION'],
      },
      masteringComment: 'HERMOSO! THE BLEND OF TRADITIONAL AND MODERN IS PERFECT!',
    },
    region: 'caribbean',
  },
  'medellin': {
    id: 'medellin',
    name: 'Medellin',
    genre: 'Trap Latino',
    level: 2,
    numInstruments: 8,
    instruments: [
      { id: 'kick6', name: 'Hard Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare6', name: 'Snare Pop', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat6', name: 'Fast Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc6', name: 'Perc Hit', type: 'perc', color: 'bg-green-500' },
      { id: 'bass6', name: 'Sub Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead6', name: 'Flute Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord6', name: 'Chord Stabs', type: 'chord', color: 'bg-blue-500' },
      { id: 'fx6', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-2.8, 0.2, 0],
    venue: 'Movistar Arena',
    mediaOutlet: 'Urban Latino',
    emoji: '🎵',
    guestProducer: {
      name: 'KAROL G',
      quote: 'TRAP LATINO IS THE NEW SOUND OF LATIN AMERICA.',
      skinTone: '#a0725f',
      topColor: '#ff1493',
      accessory: 'chain-necklace',
      genreIntro: {
        about: 'TRAP LATINO BLENDS THE AGGRESSIVE ENERGY OF TRAP WITH LATIN AMERICAN ROOTS. IT\'S THE SOUND OF THE STREETS, RAW AND ENERGETIC WITH REGGAETON RHYTHMS.',
        bpmRange: '90-100 BPM',
        tips: ['LAYER YOUR SYNTHS', 'USE LATIN PERCUSSION', 'KEEP THE ENERGY CONSTANT'],
      },
      masteringComment: 'FUEGO! THIS TRACK IS GOING TO BLOW UP. THE ENERGY IS INSANE!',
    },
    region: 'south-america',
  },
  'rio': {
    id: 'rio',
    name: 'Rio de Janeiro',
    genre: 'Funk Carioca',
    level: 3,
    numInstruments: 8,
    instruments: [
      { id: 'kick7', name: 'Funk Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare7', name: 'Snare Snap', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat7', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc7', name: 'Tambourine', type: 'perc', color: 'bg-green-500' },
      { id: 'bass7', name: 'Funk Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead7', name: 'Whistle Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord7', name: 'Synth Chord', type: 'chord', color: 'bg-blue-500' },
      { id: 'pad7', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
    ],
    position: [-1.5, -1, -0.5],
    venue: 'Maracana',
    mediaOutlet: 'Rio Baile',
    emoji: '🎊',
    guestProducer: {
      name: 'MV BILL',
      quote: 'FUNK CARIOCA IS THE VOICE OF THE FAVELAS.',
      skinTone: '#5d4e37',
      topColor: '#ffcc00',
      accessory: 'cap',
      genreIntro: {
        about: 'FUNK CARIOCA WAS BORN IN THE FAVELAS OF RIO. IT\'S A MIX OF MIAMI BASS, LATIN PERCUSSION, AND BRAZILIAN RHYTHMS. IT\'S ABOUT DANCING AND CELEBRATING LIFE.',
        bpmRange: '130-150 BPM',
        tips: ['KEEP THE RHYTHM FAST AND INFECTIOUS', 'USE BRAZILIAN PERCUSSION', 'LAYER SYNTHS FOR THAT PARTY VIBE'],
      },
      masteringComment: 'DOPE! THE RHYTHM IS CONTAGIOUS. THIS WILL MOVE THE CROWD!',
    },
    region: 'south-america',
  },
  'fortaleza': {
    id: 'fortaleza',
    name: 'Fortaleza',
    genre: 'Forró / Axé',
    level: 3,
    numInstruments: 10,
    instruments: [
      { id: 'kick8', name: 'Forro Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare8', name: 'Snare Crack', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat8', name: 'Hihat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc8a', name: 'Tamborim', type: 'perc', color: 'bg-green-500' },
      { id: 'perc8b', name: 'Pandeiro', type: 'perc', color: 'bg-green-600' },
      { id: 'bass8', name: 'Bass Line', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead8', name: 'Accordion', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord8', name: 'String Arrangement', type: 'chord', color: 'bg-blue-500' },
      { id: 'pad8', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx8', name: 'Transition', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-0.8, -1.8, -0.2],
    venue: 'Arena de Fortaleza',
    mediaOutlet: 'Axé Music Central',
    emoji: '🎸',
    guestProducer: {
      name: 'GILBERTO GIL',
      quote: 'FORRO IS THE BRAZILIAN SPIRIT IN RHYTHM.',
      skinTone: '#8d5524',
      topColor: '#0066cc',
      accessory: 'no-accessory',
      genreIntro: {
        about: 'FORRÓ IS A TRADITIONAL BRAZILIAN MUSIC AND DANCE STYLE FROM THE NORTHEAST. FORRO PARTIES ARE CALLED FESTAS JUNINAS. IT\'S A CELEBRATION OF LIFE WITH ACCORDION, PERCUSSION, AND INFECTIOUS RHYTHMS.',
        bpmRange: '120-140 BPM',
        tips: ['USE ACCORDION AS A LEAD INSTRUMENT', 'KEEP PERCUSSION TIGHT AND COMMUNICATIVE', 'BUILD ENERGY WITH LAYERED SYNTHS'],
      },
      masteringComment: 'BEAUTIFUL ARRANGEMENT! THE ACCORDION SHINES THROUGH! MUITO BOM!',
    },
    region: 'south-america',
  },
  'sao-paulo': {
    id: 'sao-paulo',
    name: 'São Paulo',
    genre: 'Minimal Techno',
    level: 3,
    numInstruments: 10,
    instruments: [
      { id: 'kick9', name: 'Minimal Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare9', name: 'Clap', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat9', name: 'Metallic Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc9a', name: 'Wood Block', type: 'perc', color: 'bg-green-500' },
      { id: 'perc9b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass9', name: 'Sine Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead9', name: 'Minimal Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'arp9', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad9', name: 'Minimal Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx9', name: 'Space FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-1.2, -1.5, -0.3],
    venue: 'SESC Pombeia',
    mediaOutlet: 'Resident Advisor Brazil',
    emoji: '🏙️',
    guestProducer: {
      name: 'RICHIE HAWTIN',
      quote: 'MINIMAL IS ABOUT SUBTLETY AND SPACE.',
      skinTone: '#d4a574',
      topColor: '#333333',
      accessory: 'headphones',
      genreIntro: {
        about: 'MINIMAL TECHNO IS THE REDUCTION OF TECHNO TO ITS ESSENCE. IT\'S ABOUT SUBTLE CHANGES, SPACE, AND BUILDING TENSION OVER LONG PERIODS. THE FOCUS IS ON TEXTURE AND GROOVE.',
        bpmRange: '120-130 BPM',
        tips: ['STRIP IT DOWN TO THE ESSENTIALS', 'USE SPACE AS AN INSTRUMENT', 'BUILD TENSION WITH SUBTLE CHANGES'],
      },
      masteringComment: 'SUBLIME. THE MINIMAL APPROACH IS PERFECT. EVERY SOUND HAS PURPOSE!',
    },
    region: 'south-america',
  },
  'luanda': {
    id: 'luanda',
    name: 'Luanda',
    genre: 'Kuduro',
    level: 3,
    numInstruments: 8,
    instruments: [
      { id: 'kick10', name: 'Kuduro Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare10', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat10', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc10', name: 'Percussion', type: 'perc', color: 'bg-green-500' },
      { id: 'bass10', name: 'Bass Line', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead10', name: 'Lead Synth', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord10', name: 'Chord Synth', type: 'chord', color: 'bg-blue-500' },
      { id: 'pad10', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
    ],
    position: [1, -1.5, 0],
    venue: 'Palácio de Vidro',
    mediaOutlet: 'Angola Baila',
    emoji: '🥁',
    guestProducer: {
      name: 'MARIZA',
      quote: 'KUDURO IS THE RHYTHM OF ANGOLA.',
      skinTone: '#5d4e37',
      topColor: '#ff6600',
      accessory: 'no-accessory',
      genreIntro: {
        about: 'KUDURO EMERGED IN LUANDA, ANGOLA IN THE 1980S. IT\'S A ENERGETIC, HIGH-TEMPO DANCE MUSIC THAT COMBINES BASS AND PERCUSSION WITH EDGY, SYNCOPATED RHYTHMS.',
        bpmRange: '130-150 BPM',
        tips: ['KEEP THE KICK PUNCHY', 'USE SYNCOPATED RHYTHMS', 'LAYER SYNTHS FOR ENERGY'],
      },
      masteringComment: 'FIRE! THE ENERGY IS PERFECT! THIS TRACK HAS ATTITUDE!',
    },
    region: 'africa',
  },
  'bogota': {
    id: 'bogota',
    name: 'Bogotá',
    genre: 'Cumbia',
    level: 4,
    numInstruments: 10,
    instruments: [
      { id: 'kick11', name: 'Cumbia Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare11', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat11', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc11a', name: 'Clave', type: 'perc', color: 'bg-green-500' },
      { id: 'perc11b', name: 'Guiro', type: 'perc', color: 'bg-green-600' },
      { id: 'bass11', name: 'Cumbia Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead11', name: 'Flute', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord11', name: 'Brass Section', type: 'chord', color: 'bg-blue-500' },
      { id: 'pad11', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx11', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-2.5, -0.8, -0.2],
    venue: 'Teatro Colón',
    mediaOutlet: 'Mundo Cumbia',
    emoji: '🎺',
    guestProducer: {
      name: 'JOE ARROYO',
      quote: 'CUMBIA IS THE SOUL OF COLOMBIA.',
      skinTone: '#a0725f',
      topColor: '#ffcc00',
      accessory: 'hat',
      genreIntro: {
        about: 'CUMBIA IS A TRADITIONAL COLOMBIAN MUSIC AND DANCE. IT HAS AFRICAN AND INDIGENOUS ROOTS. THE RHYTHM IS STEADY, THE DANCING IS SENSUAL, AND THE HORNS ADD CELEBRATION.',
        bpmRange: '90-110 BPM',
        tips: ['KEEP THE RHYTHM HYPNOTIC', 'USE BRASS FOR ENERGY', 'LET THE BASS GROOVE'],
      },
      masteringComment: 'HERMOSO! THE CUMBIA RHYTHM IS PERFECT! THE HORNS ADD SUCH CHARACTER!',
    },
    region: 'central-america',
  },
  'buenos-aires': {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    genre: 'Tango / Electrotango',
    level: 4,
    numInstruments: 12,
    instruments: [
      { id: 'kick12', name: 'Tango Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare12', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat12', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc12a', name: 'Woodblock', type: 'perc', color: 'bg-green-500' },
      { id: 'perc12b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass12', name: 'Contrabass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead12', name: 'Bandoneon', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord12', name: 'Piano', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp12', name: 'Violin Arp', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad12a', name: 'Violin Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad12b', name: 'Strings Pad', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx12', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3.2, -1.8, 0],
    venue: 'Teatro Colón',
    mediaOutlet: 'Tango Buenos Aires',
    emoji: '💃',
    guestProducer: {
      name: 'CARLOS GARDEL',
      quote: 'TANGO IS THE HEART AND SOUL OF BUENOS AIRES.',
      skinTone: '#a0725f',
      topColor: '#330000',
      accessory: 'fedora',
      genreIntro: {
        about: 'TANGO ORIGINATED IN BUENOS AIRES IN THE LATE 19TH CENTURY. IT\'S A PASSIONATE DANCE MUSIC WITH DEEP EMOTIONAL EXPRESSION. ELECTROTANGO BRINGS MODERN ELECTRONIC ELEMENTS TO TRADITIONAL TANGO.',
        bpmRange: '65-110 BPM',
        tips: ['KEEP THE EMOTION ALIVE', 'USE TRADITIONAL INSTRUMENTS', 'BLEND ELECTRONIC WITH ACOUSTIC'],
      },
      masteringComment: 'EXQUISITO! THE TANGO PASSION SHINES THROUGH! A TRUE ELECTROTANGO MASTERPIECE!',
    },
    region: 'south-america',
  },
  'santiago': {
    id: 'santiago',
    name: 'Santiago',
    genre: 'Cueca / Electronica Andina',
    level: 4,
    numInstruments: 12,
    instruments: [
      { id: 'kick13', name: 'Cueca Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare13', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat13', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc13a', name: 'Bombo', type: 'perc', color: 'bg-green-500' },
      { id: 'perc13b', name: 'Tambourine', type: 'perc', color: 'bg-green-600' },
      { id: 'bass13', name: 'Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead13', name: 'Pan Flute', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord13', name: 'Synth Chords', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp13', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad13a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad13b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx13', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3.5, -2.2, 0.3],
    venue: 'Teatro Municipal',
    mediaOutlet: 'Cueca Chile',
    emoji: '🏔️',
    guestProducer: {
      name: 'VIOLETA PARRA',
      quote: 'CUECA IS THE DANCE OF CHILE.',
      skinTone: '#a0725f',
      topColor: '#ff0066',
      accessory: 'no-accessory',
      genreIntro: {
        about: 'CUECA IS THE NATIONAL DANCE OF CHILE. IT\'S A COURTSHIP DANCE WITH ROOTS IN SPANISH AND INDIGENOUS TRADITIONS. ELECTRONICA ANDINA BLENDS TRADITIONAL CUECA WITH MODERN ELECTRONIC PRODUCTION.',
        bpmRange: '90-110 BPM',
        tips: ['USE TRADITIONAL ANDEAN INSTRUMENTS', 'KEEP THE RHYTHM ENERGETIC', 'BLEND ELECTRONIC WITH ACOUSTIC'],
      },
      masteringComment: 'HERMOSO! THE CUECA SPIRIT IS ALIVE IN THIS BEAT! MOLTO BENE!',
    },
    region: 'south-america',
  },
  'mexico-city': {
    id: 'mexico-city',
    name: 'Mexico City',
    genre: 'Banda / Regional Mexicano',
    level: 5,
    numInstruments: 12,
    instruments: [
      { id: 'kick14', name: 'Banda Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare14', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat14', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc14a', name: 'Timpani', type: 'perc', color: 'bg-green-500' },
      { id: 'perc14b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass14', name: 'Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead14', name: 'Trumpet Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord14a', name: 'Trombone', type: 'chord', color: 'bg-blue-500' },
      { id: 'chord14b', name: 'Tuba', type: 'chord', color: 'bg-blue-600' },
      { id: 'arp14', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad14', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx14', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3.8, 0.5, -0.3],
    venue: 'Auditorio Nacional',
    mediaOutlet: 'Bandamax',
    emoji: '🎺',
    guestProducer: {
      name: 'JUAN GABRIEL',
      quote: 'LA BANDA ES LA MUSICA DEL PUEBLO.',
      skinTone: '#a0725f',
      topColor: '#ff9900',
      accessory: 'hat',
      genreIntro: {
        about: 'BANDA IS A STYLE OF MEXICAN MUSIC WITH ROOTS IN THE RURAL REGIONS. IT FEATURES A LARGE BRASS SECTION INCLUDING TRUMPETS, TROMBONES, AND TUBAS. IT\'S ENERGETIC AND CELEBRATORY.',
        bpmRange: '85-110 BPM',
        tips: ['USE BIG BRASS SECTIONS', 'KEEP THE RHYTHM DRIVING', 'CELEBRATE WITH SYNTHS'],
      },
      masteringComment: '¡EXCELENTE! LA BANDA SUENA AUTENTICA Y ENERGETICA! ¡MUY BIEN!',
    },
    region: 'central-america',
  },
  'monterrey': {
    id: 'monterrey',
    name: 'Monterrey',
    genre: 'Norteño / Sierreño',
    level: 5,
    numInstruments: 14,
    instruments: [
      { id: 'kick15', name: 'Northern Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare15', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat15', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc15a', name: 'Timpani', type: 'perc', color: 'bg-green-500' },
      { id: 'perc15b', name: 'Cowbell', type: 'perc', color: 'bg-green-600' },
      { id: 'bass15', name: 'Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead15a', name: 'Accordion', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead15b', name: 'Trumpet', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord15a', name: 'Guitar Strum', type: 'chord', color: 'bg-blue-500' },
      { id: 'chord15b', name: 'Trombone', type: 'chord', color: 'bg-blue-600' },
      { id: 'arp15', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad15a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad15b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx15', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3.5, 1.2, -0.5],
    venue: 'Barrio Antiguo',
    mediaOutlet: 'Norteño Central',
    emoji: '🎻',
    guestProducer: {
      name: 'CONJUNTO PRIMAVERA',
      quote: 'LA MUSICA NORTENA ES LA VOZ DEL NORTE.',
      skinTone: '#a0725f',
      topColor: '#cc3300',
      accessory: 'sombrero',
      genreIntro: {
        about: 'NORTENO AND SIERRENO ARE TRADITIONAL MUSIC STYLES FROM NORTHERN MEXICO. THEY FEATURE THE ACCORDION AS A KEY INSTRUMENT, ALONG WITH GUITARS, BASS, AND PERCUSSION. THE RHYTHMS ARE DRIVING AND CELEBRATORY.',
        bpmRange: '85-115 BPM',
        tips: ['FEATURE THE ACCORDION', 'USE ACOUSTIC INSTRUMENTS', 'KEEP RHYTHMS DRIVING'],
      },
      masteringComment: '¡MAGNÍFICO! EL SONIDO DEL NORTE BRILLA EN ESTE TEMA! ¡AUTENTICO Y ENERGETICO!',
    },
    region: 'central-america',
  },
  'tulum': {
    id: 'tulum',
    name: 'Tulum',
    genre: 'Tropical House / Reggaeton Fusion',
    level: 5,
    numInstruments: 14,
    instruments: [
      { id: 'kick16', name: 'Tropical Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare16', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat16', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc16a', name: 'Clave', type: 'perc', color: 'bg-green-500' },
      { id: 'perc16b', name: 'Marimba', type: 'perc', color: 'bg-green-600' },
      { id: 'bass16', name: 'Tropical Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead16a', name: 'Tropical Synth', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead16b', name: 'Steel Drums', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord16a', name: 'Pad Chords', type: 'chord', color: 'bg-blue-500' },
      { id: 'chord16b', name: 'String Stabs', type: 'chord', color: 'bg-blue-600' },
      { id: 'arp16', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad16a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad16b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx16', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [-3.2, 0.8, 0.2],
    venue: 'Jungle Club',
    mediaOutlet: 'Tulum Vibes',
    emoji: '🏖️',
    guestProducer: {
      name: 'KYGO',
      quote: 'TROPICAL HOUSE IS THE SOUND OF PARADISE.',
      skinTone: '#d4a574',
      topColor: '#00ff99',
      accessory: 'sunglasses',
      genreIntro: {
        about: 'TROPICAL HOUSE IS A LAID-BACK ELECTRONIC MUSIC GENRE THAT BLENDS HOUSE MUSIC WITH TROPICAL ELEMENTS LIKE STEEL DRUMS AND REGGAE VIBES. IT\'S PERFECT FOR BEACH PARTIES AND SUNSET MOMENTS.',
        bpmRange: '95-110 BPM',
        tips: ['USE TROPICAL INSTRUMENTS LIKE STEEL DRUMS', 'KEEP THE VIBE RELAXED AND GROOVY', 'ADD REGGAE ELEMENTS FOR CHARACTER'],
      },
      masteringComment: 'BEAUTIFUL TROPICAL VIBES! THIS FEELS LIKE A BEACH SUNSET! AMAZING PRODUCTION!',
    },
    region: 'central-america',
  },
  'amsterdam': {
    id: 'amsterdam',
    name: 'Amsterdam',
    genre: 'House',
    level: 6,
    numInstruments: 12,
    instruments: [
      { id: 'kick17', name: 'House Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare17', name: 'Clap', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat17', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc17a', name: 'Cowbell', type: 'perc', color: 'bg-green-500' },
      { id: 'perc17b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass17', name: 'House Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead17', name: 'Lead Synth', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord17', name: 'Chord Synth', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp17', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad17', name: 'Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'fx17a', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx17b', name: 'Reverb Tail', type: 'fx', color: 'bg-cyan-600' },
    ],
    position: [0.5, -2, -0.8],
    venue: 'Melkweg',
    mediaOutlet: 'DJ Mag',
    emoji: '🚲',
    guestProducer: {
      name: 'TIËSTO',
      quote: 'HOUSE IS THE FUTURE. FEEL THE BEAT.',
      skinTone: '#d4a574',
      topColor: '#0066ff',
      accessory: 'headphones',
      genreIntro: {
        about: 'HOUSE MUSIC ORIGINATED IN CHICAGO AND BECAME HUGE IN AMSTERDAM AND IBIZA. IT\'S CHARACTERIZED BY A 4/4 BEAT, SOULFUL VOCALS, AND GROOVY SYNTHS. IT\'S THE SOUNDTRACK TO DANCE FLOORS WORLDWIDE.',
        bpmRange: '120-130 BPM',
        tips: ['KEEP THE FOUR-ON-THE-FLOOR KICK STEADY', 'USE SOULFUL SAMPLES', 'LAYER SYNTHS FOR DANCEFLOOR ENERGY'],
      },
      masteringComment: 'ABSOLUTE DANCEFLOOR KILLER! THE GROOVES ARE INFECTIOUS! TIËSTO WOULD BE PROUD!',
    },
    region: 'europe',
  },
  'paris': {
    id: 'paris',
    name: 'Paris',
    genre: 'Deep House / French House',
    level: 6,
    numInstruments: 12,
    instruments: [
      { id: 'kick18', name: 'Deep House Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare18', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat18', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc18a', name: 'Shaker', type: 'perc', color: 'bg-green-500' },
      { id: 'perc18b', name: 'Wood Block', type: 'perc', color: 'bg-green-600' },
      { id: 'bass18', name: 'Deep Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead18', name: 'Filtered Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord18', name: 'Vintage Keys', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp18', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad18a', name: 'Warm Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad18b', name: 'Filter Pad', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx18', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [0.8, -2.3, -0.9],
    venue: 'Palais Garnier',
    mediaOutlet: 'Les Inrocks',
    emoji: '🗼',
    guestProducer: {
      name: 'JUSTICE',
      quote: 'FRENCH HOUSE IS SOPHISTICATED AND GROOVY.',
      skinTone: '#d4a574',
      topColor: '#ff00ff',
      accessory: 'no-accessory',
      genreIntro: {
        about: 'FRENCH HOUSE (OR FRENCH TOUCH) IS A BLEND OF FUNK, DISCO, AND HOUSE MUSIC THAT EMERGED IN PARIS IN THE 1990S. IT\'S KNOWN FOR FILTERED VOCALS, VINTAGE EQUIPMENT, AND A SOPHISTICATED GROOVE.',
        bpmRange: '105-125 BPM',
        tips: ['USE FILTERED VOCALS', 'ADD VINTAGE EQUIPMENT WARMTH', 'KEEP THE GROOVE SOPHISTICATED AND SEXY'],
      },
      masteringComment: 'MAGNIFIQUE! THE FRENCH TOUCH IS UNDENIABLE! SOPHISTICATED AND GROOVY!',
    },
    region: 'europe',
  },
  'berlin': {
    id: 'berlin',
    name: 'Berlin',
    genre: 'Techno',
    level: 7,
    numInstruments: 14,
    instruments: [
      { id: 'kick19', name: '4x4 Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare19', name: 'Clap', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat19', name: 'Metallic Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc19a', name: 'Cowbell', type: 'perc', color: 'bg-green-500' },
      { id: 'perc19b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass19', name: 'Sub Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead19a', name: 'Techno Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead19b', name: 'Synth Stab', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord19', name: 'Chord Stab', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp19', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad19a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad19b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx19a', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx19b', name: 'Reverb Tail', type: 'fx', color: 'bg-cyan-600' },
    ],
    position: [1.2, -2.5, -1],
    venue: 'Berghain',
    mediaOutlet: 'Resident Advisor Berlin',
    emoji: '🏛️',
    guestProducer: {
      name: 'RICHIE HAWTIN',
      quote: 'BERLIN TECHNO IS RAW, INDUSTRIAL, AND RELENTLESS.',
      skinTone: '#d4a574',
      topColor: '#000000',
      accessory: 'headphones',
      genreIntro: {
        about: 'BERLIN TECHNO IS KNOWN FOR ITS INDUSTRIAL SOUND, DARK ATMOSPHERE, AND RELENTLESS ENERGY. IT EMERGED FROM THE WAREHOUSES AND UNDERGROUND CLUBS OF BERLIN AFTER THE FALL OF THE WALL.',
        bpmRange: '125-135 BPM',
        tips: ['KEEP IT RAW AND INDUSTRIAL', 'USE MODULATION AND FILTERS', 'BUILD HYPNOTIC TENSION'],
      },
      masteringComment: 'RAW, DARK, AND HYPNOTIC! PURE BERLIN TECHNO ENERGY! OUTSTANDING!',
    },
    region: 'europe',
  },
  'moscow': {
    id: 'moscow',
    name: 'Moscow',
    genre: 'Techno',
    level: 7,
    numInstruments: 14,
    instruments: [
      { id: 'kick20', name: 'Industrial Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare20', name: 'Snare Crunch', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat20', name: 'Metallic Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc20a', name: 'Metal Hit', type: 'perc', color: 'bg-green-500' },
      { id: 'perc20b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass20', name: 'Deep Sub Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead20a', name: 'Cold Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead20b', name: 'Stab Synth', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord20', name: 'Chord Hit', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp20', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad20a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad20b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx20a', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx20b', name: 'Noise Tail', type: 'fx', color: 'bg-cyan-600' },
    ],
    position: [2, -2.2, -0.7],
    venue: 'Propaganda Club',
    mediaOutlet: 'Resident Advisor Russia',
    emoji: '🏰',
    guestProducer: {
      name: 'SCUBA',
      quote: 'MOSCOW TECHNO IS THE BEAT OF THE FUTURE.',
      skinTone: '#d4a574',
      topColor: '#1a1a1a',
      accessory: 'headphones',
      genreIntro: {
        about: 'MOSCOW TECHNO IS INFLUENCED BY ITS HARSH WINTERS AND INDUSTRIAL PAST. IT\'S DARK, COLD, AND RELENTLESS. THE SOUND IS DYSTOPIAN AND FORWARD-THINKING.',
        bpmRange: '120-135 BPM',
        tips: ['EMBRACE THE DARKNESS', 'USE INDUSTRIAL TEXTURES', 'CREATE HYPNOTIC LOOPS'],
      },
      masteringComment: 'COLD, DARK, AND HYPNOTIC! PURE MOSCOW ENERGY! BRILLIANT!',
    },
    region: 'europe',
  },
  'london': {
    id: 'london',
    name: 'London',
    genre: 'Garage / Grime',
    level: 7,
    numInstruments: 14,
    instruments: [
      { id: 'kick21', name: 'Garage Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare21', name: 'Snare Crack', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat21', name: 'Fast Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc21a', name: 'Clap', type: 'perc', color: 'bg-green-500' },
      { id: 'perc21b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass21', name: 'Reece Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead21a', name: 'Grime Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead21b', name: 'Stab Synth', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord21', name: 'Chord Stab', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp21', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad21a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad21b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx21a', name: 'Reverb Effect', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx21b', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-600' },
    ],
    position: [0.5, -2.8, -1.1],
    venue: 'O2 Arena',
    mediaOutlet: 'Rinse FM',
    emoji: '🎤',
    guestProducer: {
      name: 'WILEY',
      quote: 'GRIME IS LONDON. LONDON IS GRIME.',
      skinTone: '#5d4e37',
      topColor: '#00ff00',
      accessory: 'gold-chain',
      genreIntro: {
        about: 'GARAGE AND GRIME EMERGED FROM LONDON\'S PIRATE RADIO STATIONS AND UNDERGROUND CLUB SCENES. GRIME IS KNOWN FOR ITS RAPID BREAKBEATS (USUALLY 140 BPM), DARK STRINGS, AND AGGRESSIVE MCS.',
        bpmRange: '135-145 BPM',
        tips: ['KEEP THE BREAKBEATS FAST AND INTRICATE', 'USE DARK MINOR KEY STRINGS', 'LEAVE SPACE FOR THE MC'],
      },
      masteringComment: 'COLD AND AGGRESSIVE! PURE LONDON GRIME! THE ENERGY IS UNMATCHED!',
    },
    region: 'europe',
  },
  'newcastle': {
    id: 'newcastle',
    name: 'Newcastle',
    genre: 'UK Hardcore / Breakcore',
    level: 7,
    numInstruments: 16,
    instruments: [
      { id: 'kick22', name: 'Hardcore Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare22', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat22', name: 'Fast Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc22a', name: 'Clap', type: 'perc', color: 'bg-green-500' },
      { id: 'perc22b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass22', name: 'Distorted Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead22a', name: 'Saw Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead22b', name: 'Hardcore Stab', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord22a', name: 'Chord Stab 1', type: 'chord', color: 'bg-blue-500' },
      { id: 'chord22b', name: 'Chord Stab 2', type: 'chord', color: 'bg-blue-600' },
      { id: 'arp22', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad22a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad22b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx22a', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx22b', name: 'Reverb Tail', type: 'fx', color: 'bg-cyan-600' },
      { id: 'fx22c', name: 'Delay', type: 'fx', color: 'bg-cyan-700' },
    ],
    position: [0.2, -3.2, -1.2],
    venue: 'Riverside Complex',
    mediaOutlet: 'Hardcore Heaven',
    emoji: '⚡',
    guestProducer: {
      name: 'DJ RATTY',
      quote: 'HARDCORE IS RELENTLESS. BREAKCORE IS CHAOS.',
      skinTone: '#d4a574',
      topColor: '#ff00ff',
      accessory: 'spiked-collar',
      genreIntro: {
        about: 'UK HARDCORE AND BREAKCORE ARE THE MOST INTENSE ELECTRONIC GENRES. THEY FEATURE DISTORTED BASS, RAPID BREAKBEATS, AND CHAOTIC ENERGY. THEY\'RE NOT FOR THE FAINT OF HEART.',
        bpmRange: '160-200 BPM',
        tips: ['PUSH THE TEMPO HIGH', 'USE DISTORTION AND CHAOS', 'EXPERIMENT WITH BREAKBEATS'],
      },
      masteringComment: 'ABSOLUTELY MENTAL! RAW HARDCORE ENERGY! BREAKCORE CHAOS AT ITS FINEST!',
    },
    region: 'europe',
  },
  'brighton': {
    id: 'brighton',
    name: 'Brighton',
    genre: 'Synthwave / Darkwave',
    level: 7,
    numInstruments: 16,
    instruments: [
      { id: 'kick23', name: 'Synth Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare23', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat23', name: 'Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc23a', name: 'Clap', type: 'perc', color: 'bg-green-500' },
      { id: 'perc23b', name: 'Shaker', type: 'perc', color: 'bg-green-600' },
      { id: 'bass23', name: 'Dark Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead23a', name: 'Neon Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'lead23b', name: 'Synth Stab', type: 'lead', color: 'bg-pink-600' },
      { id: 'chord23a', name: 'Dark Chords', type: 'chord', color: 'bg-blue-500' },
      { id: 'chord23b', name: 'Stab Synth', type: 'chord', color: 'bg-blue-600' },
      { id: 'arp23', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad23a', name: 'Dark Pad', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad23b', name: 'Synth Pad', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx23a', name: 'Filter Sweep', type: 'fx', color: 'bg-cyan-500' },
      { id: 'fx23b', name: 'Reverb Tail', type: 'fx', color: 'bg-cyan-600' },
      { id: 'fx23c', name: 'Delay', type: 'fx', color: 'bg-cyan-700' },
    ],
    position: [0, -3.1, -1.15],
    venue: 'Coalition Brighton',
    mediaOutlet: 'Darkwave Chronicles',
    emoji: '🌌',
    guestProducer: {
      name: 'CARPENTER BRUT',
      quote: 'SYNTHWAVE IS NOSTALGIA. DARKWAVE IS DREAD.',
      skinTone: '#d4a574',
      topColor: '#ff0080',
      accessory: 'sunglasses',
      genreIntro: {
        about: 'SYNTHWAVE AND DARKWAVE ARE MOODY, ATMOSPHERIC ELECTRONIC GENRES. SYNTHWAVE DRAWS INSPIRATION FROM 1980S AESTHETICS WITH NEON SYNTHS. DARKWAVE IS DARKER, MORE GOTHIC, WITH DISTORTED SYNTHS AND COLD ATMOSPHERES.',
        bpmRange: '100-130 BPM',
        tips: ['USE RETRO SYNTH SOUNDS', 'CREATE MOODY ATMOSPHERES', 'EXPERIMENT WITH NEON AND DARKNESS'],
      },
      masteringComment: 'BEAUTIFUL SYNTHWAVE NOSTALGIA MIXED WITH DARKWAVE ATMOSPHERE! STUNNING!',
    },
    region: 'europe',
  },
  'sydney': {
    id: 'sydney',
    name: 'Sydney',
    genre: 'Liquid Drum and Bass',
    level: 8,
    numInstruments: 12,
    instruments: [
      { id: 'kick24', name: 'Liquid Kick', type: 'kick', color: 'bg-red-500' },
      { id: 'snare24', name: 'Snare', type: 'snare', color: 'bg-orange-500' },
      { id: 'hat24', name: 'Fast Hi-Hat', type: 'hihat', color: 'bg-yellow-500' },
      { id: 'perc24a', name: 'Shaker', type: 'perc', color: 'bg-green-500' },
      { id: 'perc24b', name: 'Clap', type: 'perc', color: 'bg-green-600' },
      { id: 'bass24', name: 'Liquid Bass', type: 'bass', color: 'bg-purple-500' },
      { id: 'lead24', name: 'Soulful Lead', type: 'lead', color: 'bg-pink-500' },
      { id: 'chord24', name: 'Smooth Chords', type: 'chord', color: 'bg-blue-500' },
      { id: 'arp24', name: 'Arpeggiator', type: 'arp', color: 'bg-rose-500' },
      { id: 'pad24a', name: 'Pad 1', type: 'pad', color: 'bg-indigo-500' },
      { id: 'pad24b', name: 'Pad 2', type: 'pad', color: 'bg-indigo-600' },
      { id: 'fx24', name: 'Transition FX', type: 'fx', color: 'bg-cyan-500' },
    ],
    position: [4, 1, 1.5],
    venue: 'Opera House',
    mediaOutlet: 'Liquid Funk',
    emoji: '🦘',
    guestProducer: {
      name: 'CALIBRE',
      quote: 'LIQUID IS THE SOUL OF DRUM AND BASS.',
      skinTone: '#d4a574',
      topColor: '#00ccff',
      accessory: 'sunglasses',
      genreIntro: {
        about: 'LIQUID DRUM AND BASS IS A SMOOTH, SOULFUL VARIANT OF D&B. IT FEATURES FAST BREAKBEATS (USUALLY 170-180 BPM) BUT WITH JAZZY CHORDS, SOULFUL BASSLINES, AND ATMOSPHERIC PADS INSTEAD OF HARSH SYNTHS.',
        bpmRange: '170-180 BPM',
        tips: ['KEEP BREAKBEATS INTRICATE BUT SMOOTH', 'USE JAZZ CHORDS AND SOULFUL SOUNDS', 'LET THE BASSLINE GROOVE'],
      },
      masteringComment: 'BEAUTIFUL LIQUID D&B! SMOOTH YET ENERGETIC! THE SOUL AND ENERGY ARE PERFECT!',
    },
    region: 'oceania',
  },
};

export const CITIES_LIST = Object.values(CITIES).sort((a, b) => a.level - b.level);

export const LEVEL_NAMES = {
  1: 'L1 HIP HOP / DETROIT',
  2: 'L2 LATIN CARIBBEAN',
  3: 'L3 SOUTH AM / AFRICA',
  4: 'L4 ANDEAN / CLUB',
  5: 'L5 MEXICO VIBES',
  6: 'L6 EURO CLASSICS',
  7: 'L7 UNDERGROUND',
  8: 'L8 DEEP DOWN UNDER',
};

export const LEVEL_COLORS = {
  1: '#ff3399',
  2: '#ff8800',
  3: '#44cc00',
  4: '#00ccff',
  5: '#ffee00',
  6: '#cc66ff',
  7: '#ff0044',
  8: '#00ffaa',
};

export const REGIONS = {
  'north-america': {
    name: 'NORTH AMERICA',
    levels: [1],
    viewBox: '-500 -200 600 500',
  },
  'caribbean': {
    name: 'CARIBBEAN',
    levels: [2],
    viewBox: '-300 0 500 400',
  },
  'south-america': {
    name: 'SOUTH AMERICA',
    levels: [3, 4],
    viewBox: '-250 200 500 600',
  },
  'central-america': {
    name: 'MEXICO & CENTRAL AM',
    levels: [5],
    viewBox: '-400 -50 500 400',
  },
  'africa': {
    name: 'AFRICA',
    levels: [3],
    viewBox: '50 100 400 400',
  },
  'europe': {
    name: 'EUROPE',
    levels: [6, 7],
    viewBox: '100 -300 500 500',
  },
  'oceania': {
    name: 'OCEANIA',
    levels: [8],
    viewBox: '400 100 400 400',
  },
};
